# New Zealand Job Market Analysis and Prediction

## 01 - Data loading and initial exploration

This notebook loads and explores the New Zealand MBIE jobs online all vacancies quarterly June 2026 dataset.

### Objective

Understand the structure, quality, time coverage and variables of the dataset before performing data cleaning and exploratory analysis.

### Data Source

Ministry of Business, Innovation & Employment (MBIE), New Zealand.

In [1]:
from pathlib import Path
import pandas as pd

In [2]:
DATA_DIR = Path("../data/raw")

quarterly_file = DATA_DIR / "jobs-online-all-vacancies-unadjusted-quarterly-june-2026.xlsx"

In [3]:
quarterly_workbook = pd.ExcelFile(quarterly_file)
quarterly_workbook.sheet_names

['Data']

## Raw data preview

The files are initially loaded without assigning column headers so that metadata rows and the true table structure can be identified.

In [4]:
quarterly_raw = pd.read_excel(
    quarterly_file,
    sheet_name="Data",
    header=None
)

In [5]:
quarterly_raw.shape

(72, 40)

In [6]:
quarterly_raw.head(10)

,0,1,2,3,4,5,6,7,8,9,...,30,31,32,33,34,35,36,37,38,39
0,Date,Auckland,Bay of Plenty,Canterbury,Gisborne Hawke's Bay,Marlborough/NelsonTasman/West Coast,Manawatu/Wanganui-Taranaki,Northland,Otago Southland,Waikato,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,skilled,semi-skilled,low skilled,unskilled,Skilled,Unskilled,ALL,NaN,72.0,1.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2009-09-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2009-12-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2010-03-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2010-06-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2010-09-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2010-12-01 00:00:00,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,NaN,NaN,NaN

## Worksheet structure

The worksheet contains multiple groups of variables arranged horizontally. The first two rows are inspected together to identify column groups and construct meaningful column names.

In [7]:
header_map = quarterly_raw.iloc[:2].T
header_map.columns = ["row_0", "row_1"]

header_map

                                  row_0                          row_1
0                                  Date                            NaN
1                              Auckland                            NaN
2                         Bay of Plenty                            NaN
3                            Canterbury                            NaN
4                  Gisborne Hawke's Bay                            NaN
5   Marlborough/NelsonTasman/West Coast                            NaN
6            Manawatu/Wanganui-Taranaki                            NaN
7                             Northland                            NaN
8                       Otago Southland                            NaN
9                               Waikato                            NaN
10                           Wellington                            NaN
11                             Industry                     Accounting
12                                  NaN                   Construction
13                                  NaN                      Education
14                                  NaN                         Health
15                                  NaN                     Hospitalty
16                                  NaN                             IT
17                                  NaN                  Manufacturing
18                                  NaN                        Primary
19                                  NaN                          Sales
20                                  NaN                          Other
21                           OCCUPATION                       Managers
22                                  NaN                  Professionals
23                                  NaN                  Tech & Trades
24                                  NaN  Community & Personal Services
25                                  NaN      Clerical & Administration
26                                  NaN                          Sales
27                                  NaN              Machinery Drivers
28                                  NaN                      Labourers
29                                  NaN                 highly skilled
30                                  NaN                        skilled
31                                  NaN                   semi-skilled
32                                  NaN                    low skilled
33                                  NaN                      unskilled
34                                  NaN                        Skilled
35                                  NaN                      Unskilled
36                                  NaN                            ALL
37                                  NaN                            NaN
38                                  NaN                           72.0
39                                  NaN                            1.0

In [8]:
column_summary = pd.DataFrame({
    "row_0_label": quarterly_raw.iloc[0],
    "row_1_label": quarterly_raw.iloc[1],
    "non_null_count": quarterly_raw.notna().sum()
})

column_summary

,row_0_label,row_1_label,non_null_count
0,Date,NaN,69
1,Auckland,NaN,64
2,Bay of Plenty,NaN,64
3,Canterbury,NaN,64
4,Gisborne Hawke's Bay,NaN,64
5,Marlborough/NelsonTasman/West Coast,NaN,64
6,Manawatu/Wanganui-Taranaki,NaN,64
7,Northland,NaN,64
8,Otago Southland,NaN,64
9,Waikato,NaN,64
10,Wellington,NaN,64
11,Industry,Accounting,65
12,NaN,Construction,64
13,NaN,Education,64
14,NaN,Health,64
15,NaN,Hospitalty,64
16,NaN,IT,64
17,NaN,Manufacturing,64
18,NaN,Primary,64
19,NaN,Sales,64
20,NaN,Other,64
21,OCCUPATION,Managers,65
22,NaN,Professionals,64
23,NaN,Tech & Trades,64
24,NaN,Community & Personal Services,64
25,NaN,Clerical & Administration,64
26,NaN,Sales,64
27,NaN,Machinery Drivers,64
28,NaN,Labourers,64
29,NaN,highly skilled,64
30,NaN,skilled,64
31,NaN,semi-skilled,64
32,NaN,low skilled,64
33,NaN,unskilled,64
34,NaN,Skilled,64
35,NaN,Unskilled,64
36,NaN,ALL,64
37,NaN,NaN,0
38,NaN,72.0,1
39,NaN,1.0,1

In [9]:
quarterly_raw.tail()

,0,1,2,3,4,5,6,7,8,9,...,30,31,32,33,34,35,36,37,38,39
67,2025-06-01 00:00:00,104.8,245.6,163.8,116.7,203.3,209,247,310.6,198.7,...,131.8,265.3,155.1,173.3,139.7,159.6,144.3,NaN,NaN,NaN
68,2025-09-01 00:00:00,113.3,281.8,196.3,131.5,240.7,218.2,243.7,372.7,218.6,...,159.6,298.2,169.5,203.7,155,178,160.3,NaN,NaN,NaN
69,2025-12-01 00:00:00,93.2,247.3,166.2,122.1,220,205.2,237.6,337.9,191.3,...,142.5,240.3,154.2,186.5,130.9,162.3,138.6,NaN,NaN,NaN
70,2026-03-01 00:00:00,115.7,305.7,207,153.3,241.9,247.2,272.4,393.4,234.3,...,144.5,310.4,200.2,255,152.5,213.9,168.3,NaN,NaN,NaN
71,2026-06-01 00:00:00,106.8,260.2,193.1,116.1,215.7,235.1,257,346.6,217.5,...,131.4,289.6,169.7,194.3,147.4,175.9,154,NaN,NaN,NaN

In [10]:
quarterly_raw[[0, 37, 38, 39]]

                     0   37    38   39
0                  Date NaN   NaN  NaN
1                   NaN NaN  72.0  1.0
2                   NaN NaN   NaN  NaN
3                   NaN NaN   NaN  NaN
4   2009-09-01 00:00:00 NaN   NaN  NaN
..                  ...  ..   ...  ...
67  2025-06-01 00:00:00 NaN   NaN  NaN
68  2025-09-01 00:00:00 NaN   NaN  NaN
69  2025-12-01 00:00:00 NaN   NaN  NaN
70  2026-03-01 00:00:00 NaN   NaN  NaN
71  2026-06-01 00:00:00 NaN   NaN  NaN

[72 rows x 4 columns]

In [11]:
quarterly_raw[[37, 38, 39]].notna().sum()

37    0
38    1
39    1
dtype: int64

## Initial observations

- The worksheet contains 72 rows and 40 columns.
- The first two rows contain a two-level header structure.
- Columns 1–10 contain regional indices.
- Columns 11–20 contain industry indices.
- Columns 21–28 contain occupation indices.
- Columns 29–33 contain detailed skill-level indices.
- Columns 34–36 contain broader skill groupings and the overall index.
- Column 37 is completely empty.
- Columns 38 and 39 each contain only one value and appear to be spreadsheet artifacts.
- The data represents an unadjusted job-advertisement index, not actual vacancy counts.
- Cleaning will be performed on copies of the raw data.

## Cleaning the regional data

Extract the date and regional indices into a separate DataFrame, preserving the original raw data.

In [12]:
regional_raw = quarterly_raw.iloc[:, :11].copy()

regional_raw.shape

(72, 11)

In [13]:
regional_raw.head()

,0,1,2,3,4,5,6,7,8,9,10
0,Date,Auckland,Bay of Plenty,Canterbury,Gisborne Hawke's Bay,Marlborough/NelsonTasman/West Coast,Manawatu/Wanganui-Taranaki,Northland,Otago Southland,Waikato,Wellington
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2009-09-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
regional_raw.columns = regional_raw.iloc[0]

In [15]:
regional_raw.head()

,Date,Auckland,Bay of Plenty,Canterbury,Gisborne Hawke's Bay,Marlborough/NelsonTasman/West Coast,Manawatu/Wanganui-Taranaki,Northland,Otago Southland,Waikato,Wellington
0,Date,Auckland,Bay of Plenty,Canterbury,Gisborne Hawke's Bay,Marlborough/NelsonTasman/West Coast,Manawatu/Wanganui-Taranaki,Northland,Otago Southland,Waikato,Wellington
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2009-09-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
regional_clean = regional_raw.iloc[1:].copy()
regional_clean = regional_clean.dropna(how="all")

In [17]:
regional_clean.head(10)

,Date,Auckland,Bay of Plenty,Canterbury,Gisborne Hawke's Bay,Marlborough/NelsonTasman/West Coast,Manawatu/Wanganui-Taranaki,Northland,Otago Southland,Waikato,Wellington
4,2009-09-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2009-12-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2010-03-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2010-06-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2010-09-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2010-12-01 00:00:00,100,100,100,100,100,100,100,100,100,100
10,2011-03-01 00:00:00,117.4,122.6,109.5,106.3,106.5,105.2,108.5,109.4,114.6,122.7
11,2011-06-01 00:00:00,123.8,115,139.8,101.8,100,106,109.6,108.3,119.4,122.2
12,2011-09-01 00:00:00,128.2,124.7,158.5,105.2,113.2,113.4,121.2,123.9,128.1,124.6
13,2011-12-01 00:00:00,101,106,140.5,104.3,114.8,101.7,109.1,120,105.8,103.1

In [18]:
region_columns = regional_clean.columns.drop("Date")
no_regional_data = regional_clean[region_columns].isna().all(axis=1)
regional_clean.loc[no_regional_data, ["Date"]]

0                 Date
4  2009-09-01 00:00:00
5  2009-12-01 00:00:00
6  2010-03-01 00:00:00
7  2010-06-01 00:00:00
8  2010-09-01 00:00:00

In [19]:
print("Rows with no regional data:", no_regional_data.sum())

Rows with no regional data: 5

In [20]:
regional_clean = regional_clean.loc[~no_regional_data].copy()
regional_clean = regional_clean.reset_index(drop=True)

In [21]:
regional_clean.head()

,Date,Auckland,Bay of Plenty,Canterbury,Gisborne Hawke's Bay,Marlborough/NelsonTasman/West Coast,Manawatu/Wanganui-Taranaki,Northland,Otago Southland,Waikato,Wellington
0,2010-12-01 00:00:00,100,100,100,100,100,100,100,100,100,100
1,2011-03-01 00:00:00,117.4,122.6,109.5,106.3,106.5,105.2,108.5,109.4,114.6,122.7
2,2011-06-01 00:00:00,123.8,115,139.8,101.8,100,106,109.6,108.3,119.4,122.2
3,2011-09-01 00:00:00,128.2,124.7,158.5,105.2,113.2,113.4,121.2,123.9,128.1,124.6
4,2011-12-01 00:00:00,101,106,140.5,104.3,114.8,101.7,109.1,120,105.8,103.1

In [22]:
regional_clean.isna().sum()

0
Date                                   0
Auckland                               0
Bay of Plenty                          0
Canterbury                             0
Gisborne Hawke's Bay                   0
Marlborough/NelsonTasman/West Coast    0
Manawatu/Wanganui-Taranaki             0
Northland                              0
Otago Southland                        0
Waikato                                0
Wellington                             0
dtype: int64

In [23]:
regional_clean.columns.name = None

In [24]:
regional_clean.dtypes

Date                                   object
Auckland                               object
Bay of Plenty                          object
Canterbury                             object
Gisborne Hawke's Bay                   object
Marlborough/NelsonTasman/West Coast    object
Manawatu/Wanganui-Taranaki             object
Northland                              object
Otago Southland                        object
Waikato                                object
Wellington                             object
dtype: object

In [25]:
regional_clean["Date"] = pd.to_datetime(
    regional_clean["Date"],
    errors="raise"
)

In [26]:
regional_clean[region_columns] = regional_clean[region_columns].apply(
    pd.to_numeric,
    errors="raise"
)

In [27]:
regional_clean.head()

,Date,Auckland,Bay of Plenty,Canterbury,Gisborne Hawke's Bay,Marlborough/NelsonTasman/West Coast,Manawatu/Wanganui-Taranaki,Northland,Otago Southland,Waikato,Wellington
0,2010-12-01,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
1,2011-03-01,117.4,122.6,109.5,106.3,106.5,105.2,108.5,109.4,114.6,122.7
2,2011-06-01,123.8,115.0,139.8,101.8,100.0,106.0,109.6,108.3,119.4,122.2
3,2011-09-01,128.2,124.7,158.5,105.2,113.2,113.4,121.2,123.9,128.1,124.6
4,2011-12-01,101.0,106.0,140.5,104.3,114.8,101.7,109.1,120.0,105.8,103.1

In [28]:
quarters = regional_clean["Date"].dt.to_period("Q")

In [29]:
print("Rows", len(regional_clean))
print("First Quarter", quarters.min())
print("Last Quarter", quarters.max())
print("Duplicate quarters:", quarters.duplicated().sum())
print("Chronological Order", quarters.is_monotonic_increasing)

Rows 63
First Quarter 2010Q4
Last Quarter 2026Q2
Duplicate quarters: 0
Chronological Order True

In [30]:
expected_quarters = pd.period_range(
    start=quarters.min(),
    end=quarters.max(),
    freq="Q"
)

missing_quarters = expected_quarters.difference(
    pd.PeriodIndex(quarters)
)

print("Missing quarters:", missing_quarters.tolist())

Missing quarters: []

## Export the cleaned regional data

In [31]:
output_file = Path("../data/processed/regional_quarterly.csv")
regional_clean.to_csv(output_file, index=False)

print("File saved:", output_file.exists())

File saved: True

## Verify that the exported file loads correctly:

In [32]:
regional_check = pd.read_csv(output_file, parse_dates=["Date"])

pd.testing.assert_frame_equal(
    regional_clean.reset_index(drop=True),
    regional_check,
    check_dtype=False,
    check_column_type=False
)

print("Export verification passed")

Export verification passed

## Extracted the date and ten regional columns.

- Extracted the date and ten regional columns.
- Removed the repeated header and fully empty rows.
- Excluded five leading quarters with no regional observations.
- Confirmed no remaining missing values.
- Converted dates and indices to appropriate types.
- Validated 63 consecutive quarters from 2010Q4 to 2026Q2.
- Exported and verified the cleaned CSV.